var poi = {
"type": "FeatureCollection",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
                                                                                
"features": [


{ "type": "Feature", "properties": { "id": "ARTBOU0210021133", "nom": "Romainville Paddock Paris", "descriptif": "<h2>OPÉRATION MIXTE COMMERCES ET HÔTEL</h2><p><h3>Groupe FIMINCO a été sélectionné par l’agglomération EST ENSEMBLE (93) et par son aménageur SEQUANO pour réaliser un Village de Marques au sein de la ZAC de l’Horloge, de plus de 20.000 m² de surface de plancher. Le programme comprend également la construction d’un hôtel 3 étoiles de 120 chambres. Ce projet commercial d’envergure régionale porté par Groupe FIMINCO est localisé sur un site industriel classé reconverti en Village de Marques, dans un cadre authentique et ludique, à proximité de la future base régionale de Loisirs, le tout à moins de 6 kilomètres de Paris, et accessible en métro. Le Village de Marques a pu accueillir ses premiers clients fin 2019</H3>", "tel": null, "mail": null, "site_web": "https://www.fiminco.com/projets/romainville-paddock-paris/", "sous_cat": "Ensemble Mixte", "categorie": "Réalisation", "adresse": null, "adresse2": "", "cp": null, "commune": null, "photo": null, "source": "" }, "geometry": { "type": "Point", "coordinates": [ 2.42979334220439,48.89412717109143 ] } },
{ "type": "Feature", "properties": { "id": "ARTBOU0210021135", "nom": "Gare Mobipole Rueil-Malmaison", "descriptif": "<h2>OPÉRATION MIXTE AU PIED DU PÔLE MULTIMODAL</h2><p><h3>Groupe FIMINCO a réalisé une opération mixte au pied du pôle multimodal (Gare RER, Gare de Bus) de Rueil-Malmaison comprenant : un hôtel 4 étoiles à l’enseigne Okko hôtels, une résidence étudiante de 120 studios et une offre commerciale de qualité. En effet, pour que le pôle multimodal ne soit pas qu’un lieu de transit mais un véritable lieu de vie animé, les deux premiers niveaux sont occupés par une jardinerie à l’enseigne Botanic et une brasserie/restaurant. Au total, plus de 3.000 m² de commerces participent à l’attractivité du site et permettre l’émergence d’une nouvelle centralité urbaine à l’échelle de la commune.</h3>", "tel": null, "mail": null, "site_web": "https://www.fiminco.com/projets/gare-rueil-malmaison-mobipole/", "sous_cat": "Ensemble Mixte", "categorie": "Réalisation", "adresse": null, "adresse2": "", "cp": null, "commune": null, "photo": null, "source": "" }, "geometry": { "type": "Point", "coordinates": [ 2.1736607414738103,48.88710999070959  ] } },
{ "type": "Feature", "properties": { "id": "ARTBOU0210021139", "nom": "Beausoleil Hôtel 4*", "descriptif": "<h2>UN HOTEL HAUT DE GAMME AUX PORTES DE MONTE CARLO</h2><p><h3>FIMINCO développe un projet d’hôtel haut de gamme sous franchise Marriott sur la commune de Beausoleil, à proximité immédiate de Monte-Carlo. Le programme comprend la réalisation de 135 chambres, un roof top avec piscine, espace solarium et restaurant panoramique, un espace spa – hammam – fitness, un espaces restauration, ainsi qu’un parking en sous-sol.</h3>", "tel": null, "mail": null, "site_web": "https://www.fiminco.com/projets/beausoleil-hotel-4-etoiles-2/", "sous_cat": "Hôtel", "categorie": "Projet", "adresse": null, "adresse2": "", "cp": null, "commune": null, "photo": null, "source": "" }, "geometry": { "type": "Point", "coordinates": [ 7.423952532208541,43.741489148333656 ] } },


]
};